test_cases_file: test_cases.csv #test_cases.yaml

log:
  failure: 
    path: logs/failure.log
    header: datetime|testfile|id|expected_unique|actual_unique
  summary: 
    path: logs/summary.log
    header: datetime|testfile|total|fail
  format: "%(asctime)s|%(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
  